// Code generated by counterfeiter. DO NOT EDIT.
package mock

import (
	"sync"

	hedera "github.com/hashgraph/hedera-sdk-go"
)

type ConsensusClient struct {
	CloseStub        func() error
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	closeReturns struct {
		result1 error
	}
	closeReturnsOnCall map[int]struct {
		result1 error
	}
	SubmitConsensusMessageStub        func([]byte, *hedera.ConsensusTopicID) error
	submitConsensusMessageMutex       sync.RWMutex
	submitConsensusMessageArgsForCall []struct {
		arg1 []byte
		arg2 *hedera.ConsensusTopicID
	}
	submitConsensusMessageReturns struct {
		result1 error
	}
	submitConsensusMessageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *ConsensusClient) Close() error {
	fake.closeMutex.Lock()
	ret, specificReturn := fake.closeReturnsOnCall[len(fake.closeArgsForCall)]
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if fake.CloseStub != nil {
		return fake.CloseStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.closeReturns
	return fakeReturns.result1
}

func (fake *ConsensusClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *ConsensusClient) CloseCalls(stub func() error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *ConsensusClient) CloseReturns(result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	fake.closeReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConsensusClient) CloseReturnsOnCall(i int, result1 error) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = nil
	if fake.closeReturnsOnCall == nil {
		fake.closeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.closeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConsensusClient) SubmitConsensusMessage(arg1 []byte, arg2 *hedera.ConsensusTopicID) error {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.submitConsensusMessageMutex.Lock()
	ret, specificReturn := fake.submitConsensusMessageReturnsOnCall[len(fake.submitConsensusMessageArgsForCall)]
	fake.submitConsensusMessageArgsForCall = append(fake.submitConsensusMessageArgsForCall, struct {
		arg1 []byte
		arg2 *hedera.ConsensusTopicID
	}{arg1Copy, arg2})
	fake.recordInvocation("SubmitConsensusMessage", []interface{}{arg1Copy, arg2})
	fake.submitConsensusMessageMutex.Unlock()
	if fake.SubmitConsensusMessageStub != nil {
		return fake.SubmitConsensusMessageStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.submitConsensusMessageReturns
	return fakeReturns.result1
}

func (fake *ConsensusClient) SubmitConsensusMessageCallCount() int {
	fake.submitConsensusMessageMutex.RLock()
	defer fake.submitConsensusMessageMutex.RUnlock()
	return len(fake.submitConsensusMessageArgsForCall)
}

func (fake *ConsensusClient) SubmitConsensusMessageCalls(stub func([]byte, *hedera.ConsensusTopicID) error) {
	fake.submitConsensusMessageMutex.Lock()
	defer fake.submitConsensusMessageMutex.Unlock()
	fake.SubmitConsensusMessageStub = stub
}

func (fake *ConsensusClient) SubmitConsensusMessageArgsForCall(i int) ([]byte, *hedera.ConsensusTopicID) {
	fake.submitConsensusMessageMutex.RLock()
	defer fake.submitConsensusMessageMutex.RUnlock()
	argsForCall := fake.submitConsensusMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *ConsensusClient) SubmitConsensusMessageReturns(result1 error) {
	fake.submitConsensusMessageMutex.Lock()
	defer fake.submitConsensusMessageMutex.Unlock()
	fake.SubmitConsensusMessageStub = nil
	fake.submitConsensusMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *ConsensusClient) SubmitConsensusMessageReturnsOnCall(i int, result1 error) {
	fake.submitConsensusMessageMutex.Lock()
	defer fake.submitConsensusMessageMutex.Unlock()
	fake.SubmitConsensusMessageStub = nil
	if fake.submitConsensusMessageReturnsOnCall == nil {
		fake.submitConsensusMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.submitConsensusMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *ConsensusClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.submitConsensusMessageMutex.RLock()
	defer fake.submitConsensusMessageMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *ConsensusClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
