// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hcs.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HcsMessageRegular_Class int32

const (
	HcsMessageRegular_NORMAL HcsMessageRegular_Class = 0
	HcsMessageRegular_CONFIG HcsMessageRegular_Class = 1
)

var HcsMessageRegular_Class_name = map[int32]string{
	0: "NORMAL",
	1: "CONFIG",
}

var HcsMessageRegular_Class_value = map[string]int32{
	"NORMAL": 0,
	"CONFIG": 1,
}

func (x HcsMessageRegular_Class) String() string {
	return proto.EnumName(HcsMessageRegular_Class_name, int32(x))
}

func (HcsMessageRegular_Class) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{1, 0}
}

// HcsMessage is a wrapper type for the messages that the HCS-based
// orderer deals with.
type HcsMessage struct {
	// Types that are valid to be assigned to Type:
	//	*HcsMessage_Regular
	//	*HcsMessage_TimeToCut
	//	*HcsMessage_OrdererStarted
	Type                 isHcsMessage_Type `protobuf_oneof:"Type"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HcsMessage) Reset()         { *m = HcsMessage{} }
func (m *HcsMessage) String() string { return proto.CompactTextString(m) }
func (*HcsMessage) ProtoMessage()    {}
func (*HcsMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{0}
}

func (m *HcsMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsMessage.Unmarshal(m, b)
}
func (m *HcsMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsMessage.Marshal(b, m, deterministic)
}
func (m *HcsMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsMessage.Merge(m, src)
}
func (m *HcsMessage) XXX_Size() int {
	return xxx_messageInfo_HcsMessage.Size(m)
}
func (m *HcsMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsMessage.DiscardUnknown(m)
}

var xxx_messageInfo_HcsMessage proto.InternalMessageInfo

type isHcsMessage_Type interface {
	isHcsMessage_Type()
}

type HcsMessage_Regular struct {
	Regular *HcsMessageRegular `protobuf:"bytes,1,opt,name=regular,proto3,oneof"`
}

type HcsMessage_TimeToCut struct {
	TimeToCut *HcsMessageTimeToCut `protobuf:"bytes,2,opt,name=time_to_cut,json=timeToCut,proto3,oneof"`
}

type HcsMessage_OrdererStarted struct {
	OrdererStarted *HcsMessageOrdererStarted `protobuf:"bytes,3,opt,name=orderer_started,json=ordererStarted,proto3,oneof"`
}

func (*HcsMessage_Regular) isHcsMessage_Type() {}

func (*HcsMessage_TimeToCut) isHcsMessage_Type() {}

func (*HcsMessage_OrdererStarted) isHcsMessage_Type() {}

func (m *HcsMessage) GetType() isHcsMessage_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *HcsMessage) GetRegular() *HcsMessageRegular {
	if x, ok := m.GetType().(*HcsMessage_Regular); ok {
		return x.Regular
	}
	return nil
}

func (m *HcsMessage) GetTimeToCut() *HcsMessageTimeToCut {
	if x, ok := m.GetType().(*HcsMessage_TimeToCut); ok {
		return x.TimeToCut
	}
	return nil
}

func (m *HcsMessage) GetOrdererStarted() *HcsMessageOrdererStarted {
	if x, ok := m.GetType().(*HcsMessage_OrdererStarted); ok {
		return x.OrdererStarted
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*HcsMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*HcsMessage_Regular)(nil),
		(*HcsMessage_TimeToCut)(nil),
		(*HcsMessage_OrdererStarted)(nil),
	}
}

// HcsMessageRegular wraps a marshalled envelope.
type HcsMessageRegular struct {
	Payload              []byte                  `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ConfigSeq            uint64                  `protobuf:"varint,2,opt,name=config_seq,json=configSeq,proto3" json:"config_seq,omitempty"`
	Class                HcsMessageRegular_Class `protobuf:"varint,3,opt,name=class,proto3,enum=proto.HcsMessageRegular_Class" json:"class,omitempty"`
	OriginalSeq          uint64                  `protobuf:"varint,4,opt,name=original_seq,json=originalSeq,proto3" json:"original_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *HcsMessageRegular) Reset()         { *m = HcsMessageRegular{} }
func (m *HcsMessageRegular) String() string { return proto.CompactTextString(m) }
func (*HcsMessageRegular) ProtoMessage()    {}
func (*HcsMessageRegular) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{1}
}

func (m *HcsMessageRegular) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsMessageRegular.Unmarshal(m, b)
}
func (m *HcsMessageRegular) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsMessageRegular.Marshal(b, m, deterministic)
}
func (m *HcsMessageRegular) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsMessageRegular.Merge(m, src)
}
func (m *HcsMessageRegular) XXX_Size() int {
	return xxx_messageInfo_HcsMessageRegular.Size(m)
}
func (m *HcsMessageRegular) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsMessageRegular.DiscardUnknown(m)
}

var xxx_messageInfo_HcsMessageRegular proto.InternalMessageInfo

func (m *HcsMessageRegular) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *HcsMessageRegular) GetConfigSeq() uint64 {
	if m != nil {
		return m.ConfigSeq
	}
	return 0
}

func (m *HcsMessageRegular) GetClass() HcsMessageRegular_Class {
	if m != nil {
		return m.Class
	}
	return HcsMessageRegular_NORMAL
}

func (m *HcsMessageRegular) GetOriginalSeq() uint64 {
	if m != nil {
		return m.OriginalSeq
	}
	return 0
}

// TODO: a fragment key is needed to identify the subject so as to handle
// the case that different messages are fragmented by different subjects with
// the same fragment_id
type HcsMessageFragment struct {
	Fragment             []byte   `protobuf:"bytes,1,opt,name=fragment,proto3" json:"fragment,omitempty"`
	FragmentKey          []byte   `protobuf:"bytes,2,opt,name=fragment_key,json=fragmentKey,proto3" json:"fragment_key,omitempty"`
	FragmentId           uint64   `protobuf:"fixed64,3,opt,name=fragment_id,json=fragmentId,proto3" json:"fragment_id,omitempty"`
	Sequence             uint32   `protobuf:"fixed32,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TotalFragments       uint32   `protobuf:"fixed32,5,opt,name=total_fragments,json=totalFragments,proto3" json:"total_fragments,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HcsMessageFragment) Reset()         { *m = HcsMessageFragment{} }
func (m *HcsMessageFragment) String() string { return proto.CompactTextString(m) }
func (*HcsMessageFragment) ProtoMessage()    {}
func (*HcsMessageFragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{2}
}

func (m *HcsMessageFragment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsMessageFragment.Unmarshal(m, b)
}
func (m *HcsMessageFragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsMessageFragment.Marshal(b, m, deterministic)
}
func (m *HcsMessageFragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsMessageFragment.Merge(m, src)
}
func (m *HcsMessageFragment) XXX_Size() int {
	return xxx_messageInfo_HcsMessageFragment.Size(m)
}
func (m *HcsMessageFragment) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsMessageFragment.DiscardUnknown(m)
}

var xxx_messageInfo_HcsMessageFragment proto.InternalMessageInfo

func (m *HcsMessageFragment) GetFragment() []byte {
	if m != nil {
		return m.Fragment
	}
	return nil
}

func (m *HcsMessageFragment) GetFragmentKey() []byte {
	if m != nil {
		return m.FragmentKey
	}
	return nil
}

func (m *HcsMessageFragment) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *HcsMessageFragment) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *HcsMessageFragment) GetTotalFragments() uint32 {
	if m != nil {
		return m.TotalFragments
	}
	return 0
}

// HcsMessageTimeToCut is used to signal to the orderers that it is time to
// cut block <block_number>.
type HcsMessageTimeToCut struct {
	BlockNumber          uint64   `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HcsMessageTimeToCut) Reset()         { *m = HcsMessageTimeToCut{} }
func (m *HcsMessageTimeToCut) String() string { return proto.CompactTextString(m) }
func (*HcsMessageTimeToCut) ProtoMessage()    {}
func (*HcsMessageTimeToCut) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{3}
}

func (m *HcsMessageTimeToCut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsMessageTimeToCut.Unmarshal(m, b)
}
func (m *HcsMessageTimeToCut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsMessageTimeToCut.Marshal(b, m, deterministic)
}
func (m *HcsMessageTimeToCut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsMessageTimeToCut.Merge(m, src)
}
func (m *HcsMessageTimeToCut) XXX_Size() int {
	return xxx_messageInfo_HcsMessageTimeToCut.Size(m)
}
func (m *HcsMessageTimeToCut) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsMessageTimeToCut.DiscardUnknown(m)
}

var xxx_messageInfo_HcsMessageTimeToCut proto.InternalMessageInfo

func (m *HcsMessageTimeToCut) GetBlockNumber() uint64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type HcsMessageOrdererStarted struct {
	OrdererIdentity      []byte   `protobuf:"bytes,1,opt,name=orderer_identity,json=ordererIdentity,proto3" json:"orderer_identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HcsMessageOrdererStarted) Reset()         { *m = HcsMessageOrdererStarted{} }
func (m *HcsMessageOrdererStarted) String() string { return proto.CompactTextString(m) }
func (*HcsMessageOrdererStarted) ProtoMessage()    {}
func (*HcsMessageOrdererStarted) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{4}
}

func (m *HcsMessageOrdererStarted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsMessageOrdererStarted.Unmarshal(m, b)
}
func (m *HcsMessageOrdererStarted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsMessageOrdererStarted.Marshal(b, m, deterministic)
}
func (m *HcsMessageOrdererStarted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsMessageOrdererStarted.Merge(m, src)
}
func (m *HcsMessageOrdererStarted) XXX_Size() int {
	return xxx_messageInfo_HcsMessageOrdererStarted.Size(m)
}
func (m *HcsMessageOrdererStarted) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsMessageOrdererStarted.DiscardUnknown(m)
}

var xxx_messageInfo_HcsMessageOrdererStarted proto.InternalMessageInfo

func (m *HcsMessageOrdererStarted) GetOrdererIdentity() []byte {
	if m != nil {
		return m.OrdererIdentity
	}
	return nil
}

// HcsMetadata is encoded into the ORDERER block to keep track of HCS-related
// metadata associated with this block.
type HcsMetadata struct {
	// lastTimestampPersisted is the used to keep track of the timestamp of
	// the last ordered message in the last block so when an HCS-based orderer
	// boots up, it knows from when to retrieve ordererd messages
	LastConsensusTimestampPersisted *timestamp.Timestamp `protobuf:"bytes,1,opt,name=last_consensus_timestamp_persisted,json=lastConsensusTimestampPersisted,proto3" json:"last_consensus_timestamp_persisted,omitempty"`
	LastOriginalSequenceProcessed   uint64               `protobuf:"varint,2,opt,name=last_original_sequence_processed,json=lastOriginalSequenceProcessed,proto3" json:"last_original_sequence_processed,omitempty"`
	LastResubmittedConfigSequence   uint64               `protobuf:"varint,3,opt,name=last_resubmitted_config_sequence,json=lastResubmittedConfigSequence,proto3" json:"last_resubmitted_config_sequence,omitempty"`
	// last fragment free consensus timestamp is the consensus timestamp of the last
	// fragment free block
	LastFragmentFreeConsensusTimestampPersisted *timestamp.Timestamp `protobuf:"bytes,4,opt,name=last_fragment_free_consensus_timestamp_persisted,json=lastFragmentFreeConsensusTimestampPersisted,proto3" json:"last_fragment_free_consensus_timestamp_persisted,omitempty"`
	XXX_NoUnkeyedLiteral                        struct{}             `json:"-"`
	XXX_unrecognized                            []byte               `json:"-"`
	XXX_sizecache                               int32                `json:"-"`
}

func (m *HcsMetadata) Reset()         { *m = HcsMetadata{} }
func (m *HcsMetadata) String() string { return proto.CompactTextString(m) }
func (*HcsMetadata) ProtoMessage()    {}
func (*HcsMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{5}
}

func (m *HcsMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsMetadata.Unmarshal(m, b)
}
func (m *HcsMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsMetadata.Marshal(b, m, deterministic)
}
func (m *HcsMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsMetadata.Merge(m, src)
}
func (m *HcsMetadata) XXX_Size() int {
	return xxx_messageInfo_HcsMetadata.Size(m)
}
func (m *HcsMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_HcsMetadata proto.InternalMessageInfo

func (m *HcsMetadata) GetLastConsensusTimestampPersisted() *timestamp.Timestamp {
	if m != nil {
		return m.LastConsensusTimestampPersisted
	}
	return nil
}

func (m *HcsMetadata) GetLastOriginalSequenceProcessed() uint64 {
	if m != nil {
		return m.LastOriginalSequenceProcessed
	}
	return 0
}

func (m *HcsMetadata) GetLastResubmittedConfigSequence() uint64 {
	if m != nil {
		return m.LastResubmittedConfigSequence
	}
	return 0
}

func (m *HcsMetadata) GetLastFragmentFreeConsensusTimestampPersisted() *timestamp.Timestamp {
	if m != nil {
		return m.LastFragmentFreeConsensusTimestampPersisted
	}
	return nil
}

type HcsConfigMetadata struct {
	// HCS topic ID in the format of shard.realm.num
	TopicID              string   `protobuf:"bytes,1,opt,name=TopicID,proto3" json:"TopicID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HcsConfigMetadata) Reset()         { *m = HcsConfigMetadata{} }
func (m *HcsConfigMetadata) String() string { return proto.CompactTextString(m) }
func (*HcsConfigMetadata) ProtoMessage()    {}
func (*HcsConfigMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a1dde7c60075de7, []int{6}
}

func (m *HcsConfigMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HcsConfigMetadata.Unmarshal(m, b)
}
func (m *HcsConfigMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HcsConfigMetadata.Marshal(b, m, deterministic)
}
func (m *HcsConfigMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HcsConfigMetadata.Merge(m, src)
}
func (m *HcsConfigMetadata) XXX_Size() int {
	return xxx_messageInfo_HcsConfigMetadata.Size(m)
}
func (m *HcsConfigMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_HcsConfigMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_HcsConfigMetadata proto.InternalMessageInfo

func (m *HcsConfigMetadata) GetTopicID() string {
	if m != nil {
		return m.TopicID
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.HcsMessageRegular_Class", HcsMessageRegular_Class_name, HcsMessageRegular_Class_value)
	proto.RegisterType((*HcsMessage)(nil), "proto.HcsMessage")
	proto.RegisterType((*HcsMessageRegular)(nil), "proto.HcsMessageRegular")
	proto.RegisterType((*HcsMessageFragment)(nil), "proto.HcsMessageFragment")
	proto.RegisterType((*HcsMessageTimeToCut)(nil), "proto.HcsMessageTimeToCut")
	proto.RegisterType((*HcsMessageOrdererStarted)(nil), "proto.HcsMessageOrdererStarted")
	proto.RegisterType((*HcsMetadata)(nil), "proto.HcsMetadata")
	proto.RegisterType((*HcsConfigMetadata)(nil), "proto.HcsConfigMetadata")
}

func init() { proto.RegisterFile("hcs.proto", fileDescriptor_4a1dde7c60075de7) }

var fileDescriptor_4a1dde7c60075de7 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x73, 0xd3, 0x30,
	0x10, 0x8d, 0x69, 0x3e, 0xc8, 0xa6, 0xd3, 0x16, 0x71, 0xf1, 0x74, 0xa6, 0xa4, 0xf8, 0x02, 0x0c,
	0x43, 0xc2, 0x94, 0x1e, 0x60, 0xe0, 0x42, 0x03, 0x6d, 0x02, 0xb4, 0xe9, 0xa8, 0x39, 0x71, 0xf1,
	0x28, 0xf6, 0xc6, 0xf1, 0xd4, 0xb6, 0x1c, 0x49, 0x3e, 0xe4, 0xc8, 0x9d, 0x3f, 0xc4, 0x1f, 0xe0,
	0x17, 0xf0, 0x83, 0x18, 0x4b, 0x96, 0x03, 0x53, 0x4a, 0x4f, 0xd6, 0xbe, 0x3c, 0x3d, 0xad, 0xf6,
	0x3d, 0x05, 0xba, 0xcb, 0x40, 0x0e, 0x72, 0xc1, 0x15, 0x27, 0x2d, 0xfd, 0xd9, 0xef, 0x47, 0x9c,
	0x47, 0x09, 0x0e, 0x75, 0x35, 0x2f, 0x16, 0x43, 0x15, 0xa7, 0x28, 0x15, 0x4b, 0x73, 0xc3, 0xf3,
	0x7e, 0x39, 0x00, 0xe3, 0x40, 0x9e, 0xa3, 0x94, 0x2c, 0x42, 0x72, 0x0c, 0x1d, 0x81, 0x51, 0x91,
	0x30, 0xe1, 0x3a, 0x87, 0xce, 0xd3, 0xde, 0x91, 0x6b, 0x78, 0x83, 0x0d, 0x87, 0x9a, 0xdf, 0xc7,
	0x0d, 0x6a, 0xa9, 0xe4, 0x1d, 0xf4, 0x4a, 0x5d, 0x5f, 0x71, 0x3f, 0x28, 0x94, 0x7b, 0x4f, 0xef,
	0xdc, 0xbf, 0xb1, 0x73, 0x16, 0xa7, 0x38, 0xe3, 0xa3, 0x42, 0x8d, 0x1b, 0xb4, 0xab, 0x6c, 0x41,
	0x3e, 0xc1, 0x2e, 0x17, 0x21, 0x0a, 0x14, 0xbe, 0x54, 0x4c, 0x28, 0x0c, 0xdd, 0x2d, 0xad, 0xd0,
	0xbf, 0xa1, 0x30, 0x35, 0xbc, 0x2b, 0x43, 0x1b, 0x37, 0xe8, 0x0e, 0xff, 0x0b, 0x39, 0x69, 0x43,
	0x73, 0xb6, 0xce, 0xd1, 0xfb, 0xe9, 0xc0, 0x83, 0x1b, 0x2d, 0x13, 0x17, 0x3a, 0x39, 0x5b, 0x27,
	0x9c, 0x85, 0xfa, 0x76, 0xdb, 0xd4, 0x96, 0xe4, 0x00, 0x20, 0xe0, 0xd9, 0x22, 0x8e, 0x7c, 0x89,
	0x2b, 0x7d, 0x81, 0x26, 0xed, 0x1a, 0xe4, 0x0a, 0x57, 0xe4, 0x18, 0x5a, 0x41, 0xc2, 0xa4, 0xd4,
	0x8d, 0xed, 0x1c, 0x3d, 0xba, 0x6d, 0x28, 0x83, 0x51, 0xc9, 0xa2, 0x86, 0x4c, 0x1e, 0xc3, 0x36,
	0x17, 0x71, 0x14, 0x67, 0x2c, 0xd1, 0xb2, 0x4d, 0x2d, 0xdb, 0xb3, 0xd8, 0x15, 0xae, 0xbc, 0x3e,
	0xb4, 0xf4, 0x16, 0x02, 0xd0, 0xbe, 0x98, 0xd2, 0xf3, 0xf7, 0x5f, 0xf6, 0x1a, 0xe5, 0x7a, 0x34,
	0xbd, 0x38, 0x9d, 0x9c, 0xed, 0x39, 0xde, 0x0f, 0x07, 0xc8, 0xe6, 0x98, 0x53, 0xc1, 0xa2, 0x14,
	0x33, 0x45, 0xf6, 0xe1, 0xfe, 0xa2, 0x5a, 0x57, 0x57, 0xa9, 0xeb, 0xf2, 0x58, 0xbb, 0xf6, 0xaf,
	0x71, 0xad, 0x6f, 0xb3, 0x4d, 0x7b, 0x16, 0xfb, 0x8c, 0x6b, 0xd2, 0x87, 0xba, 0xf4, 0x63, 0x33,
	0xee, 0x36, 0x05, 0x0b, 0x4d, 0xc2, 0x52, 0x5f, 0xe2, 0xaa, 0xc0, 0x2c, 0x40, 0xdd, 0x76, 0x87,
	0xd6, 0x35, 0x79, 0x02, 0xbb, 0x8a, 0x2b, 0x96, 0xf8, 0x96, 0x2f, 0xdd, 0x96, 0xa6, 0xec, 0x68,
	0xd8, 0xf6, 0x28, 0xbd, 0xd7, 0xf0, 0xf0, 0x1f, 0xe6, 0x97, 0xfd, 0xcd, 0x13, 0x1e, 0x5c, 0xfb,
	0x59, 0x91, 0xce, 0xd1, 0x04, 0xad, 0x49, 0x7b, 0x1a, 0xbb, 0xd0, 0x90, 0xf7, 0x11, 0xdc, 0xdb,
	0x4c, 0x27, 0xcf, 0x60, 0xcf, 0xc6, 0x25, 0x0e, 0x31, 0x53, 0xb1, 0x5a, 0x57, 0x23, 0xb0, 0x31,
	0x9a, 0x54, 0xb0, 0xf7, 0x7d, 0x0b, 0x7a, 0x5a, 0x47, 0xb1, 0x90, 0x29, 0x46, 0x22, 0xf0, 0x12,
	0x26, 0x95, 0x1f, 0xf0, 0x4c, 0x62, 0x26, 0x0b, 0xe9, 0xd7, 0xcf, 0xc1, 0xcf, 0x51, 0xc8, 0x58,
	0x96, 0xe1, 0x73, 0xaa, 0xf8, 0x9a, 0xa7, 0x33, 0xb0, 0x4f, 0x67, 0x30, 0xb3, 0x5c, 0xda, 0x2f,
	0x55, 0x46, 0x56, 0xa4, 0xc6, 0x2f, 0xad, 0x04, 0x39, 0x83, 0x43, 0x7d, 0xd0, 0x9f, 0xf6, 0xeb,
	0xe1, 0xf9, 0xb9, 0xe0, 0x01, 0x4a, 0x89, 0x61, 0x15, 0xb2, 0x83, 0x92, 0x37, 0xdd, 0x24, 0x42,
	0xb3, 0x2e, 0x2d, 0xa9, 0x16, 0x12, 0x28, 0x8b, 0x79, 0x1a, 0x2b, 0x85, 0xa1, 0xbf, 0x09, 0xaa,
	0xf1, 0x67, 0x6b, 0x23, 0x44, 0x37, 0xb4, 0x91, 0x0d, 0xaf, 0x31, 0xed, 0x9b, 0x03, 0x2f, 0xb5,
	0x52, 0xed, 0xfb, 0x42, 0x20, 0xde, 0x31, 0x89, 0xe6, 0x9d, 0x93, 0x78, 0x5e, 0x6a, 0x5a, 0xc7,
	0x4f, 0x05, 0xe2, 0x7f, 0xa6, 0xe2, 0xbd, 0xd0, 0x6f, 0xd2, 0x34, 0x56, 0x7b, 0xe2, 0x42, 0x67,
	0xc6, 0xf3, 0x38, 0x98, 0x7c, 0xd0, 0x83, 0xef, 0x52, 0x5b, 0x9e, 0xbc, 0xfd, 0xfa, 0x26, 0x8a,
	0xd5, 0xb2, 0x98, 0x0f, 0x02, 0x9e, 0x0e, 0x97, 0xeb, 0x1c, 0x45, 0x82, 0x61, 0x84, 0x62, 0xb8,
	0x60, 0x73, 0x11, 0x07, 0xc3, 0xca, 0xee, 0x61, 0x7d, 0x89, 0xe1, 0x32, 0x90, 0xd5, 0x5f, 0x5d,
	0x5b, 0x7f, 0x5e, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xea, 0xb5, 0x66, 0x59, 0x13, 0x05, 0x00,
	0x00,
}
